### ISSUE TITLE
Crash when trying to install package

### ISSUE THREAD

**Issue by spacekookie** [XenGi/pac#1]
To replicate:

```console

 ❤ (idenna) ~> pac intel gpu                                                                     
1 community/intel-gpu-tools 1.16-1
  Tools for development and testing of the Intel DRM driver
2 aur/beignet 1.3.0-1 (44, 3.70)
  An open source OpenCL implementation for Intel IvyBridge+ iGPUs
3 aur/systemd-vgaswitcheroo-units 1.3-1 (5, 0.38)
  Disable discrete GPU at boot for AMD/NVIDIA & Intel dual stuff. This is based on the old AUR package that was not migrated to AUR4.
4 aur/beignet-git 1.0.0.r799.gcf95b44-1 (2, 0.00)
  A GPGPU System for Intel Ivybridge GPUs
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 1
Traceback (most recent call last):
  File "/usr/bin/pac", line 200, in <module>
    install(numbers, entries)
  File "/usr/bin/pac", line 157, in install
    call(args.extend(names), shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1210, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable
(

```

**Comment by XenGi** [comment]
Should be fixed with recent versions.
