### ISSUE TITLE
Crashing when using autoremove

### ISSUE THREAD

**Issue by spacekookie** [XenGi/pac#2]
```
 ❤ (idenna) ~> pac -a
Traceback (most recent call last):
  File "/usr/bin/pac", line 188, in <module>
    autoremove()
  File "/usr/bin/pac", line 164, in autoremove
    call(f'pacaur -Rs {" ".join(orphans)}')
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 36] File name too long
```

**Comment by XenGi** [comment]
fixed by #3
